id: P004641
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC26
  title: དབུ་མ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་ལེགས་བཤད་རྗེས་འབྲང་།
  author: ''
  volumes:
    d93cffd304894836a81ee6127066409a:
      image_group_id: I2PD18434
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
