id: P004641
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:46:04.238341
source_metadata:
  id: bdr:W1AC26
  title: དབུ་མ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་ལེགས་བཤད་རྗེས་འབྲང་།
  author: ''
  volumes:
    d93cffd304894836a81ee6127066409a:
      image_group_id: I2PD18434
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
